/* Terapeutas */
export const FETCH_PERFIL_SUCCESS = 'FETCH_PERFIL_SUCCESS';
export const FETCH_PERFIL_FAILURE = 'FETCH_PERFIL_FAILURE';
export const FETCH_PERFILES_SUCCESS = 'FETCH_PERFILES_SUCCESS';
export const FETCH_PERFILES_FAILURE = 'FETCH_SESIONES_FAILURE';
export const PUT_PERFIL_SUCCESS = 'PUT_PERFIL_SUCCESS';
export const PUT_PERFIL_FAILURE = 'PUT_PERFIL_FAILURE';

/* Infomes */
export const FETCH_NUMERO_SESIONES_MES_SUCCESS = 'FETCH_NUMERO_SESIONES_MES_SUCCESS';
export const FETCH_NUMERO_SESIONES_MES_FAILURE = 'FETCH_NUMERO_SESIONES_MES_FAILURE';
export const FETCH_NUMERO_PACIENTES_ACTIVOS_SUCCESS = 'FETCH_NUMERO_PACIENTES_ACTIVOS_SUCCESS';
export const FETCH_NUMERO_PACIENTES_ACTIVOS_FAILURE = 'FETCH_NUMERO_PACIENTES_ACTIVOS_FAILURE';
export const FETCH_NUMERO_SESIONES_ANUALES_SUCCESS = 'FETCH_NUMERO_SESIONES_ANUALES_SUCCESS';
export const FETCH_NUMERO_SESIONES_ANUALES_FAILURE = 'FETCH_NUMERO_SESIONES_ANUALES_FAILURE';

/* Terapia */
export const FETCH_SESION_SUCCESS = 'FETCH_SESION_SUCCESS';
export const FETCH_SESION_FAILURE = 'FETCH_SESION_FAILURE';
export const FETCH_SESIONES_SUCCESS = 'FETCH_SESIONES_SUCCESS';
export const FETCH_SESIONES_FAILURE = 'FETCH_SESIONES_FAILURE';
export const ADD_SESION_SUCCESS = 'ADD_SESION_SUCCESS';
export const ADD_SESION_FAILURE = 'ADD_SESION_FAILURE';
export const FETCH_TERAPIA_SUCCESS = 'FETCH_TERAPIA_SUCCESS';
export const FETCH_TERAPIA_FAILURE = 'FETCH_TERAPIA_FAILURE';
export const POST_TERAPIA_SUCCESS = 'PUT_TERAPIA_SUCCESS';
export const POST_TERAPIA_FAILURE = 'PUT_TERAPIA_FAILURE';
export const PUT_TERAPIA_SUCCESS = 'PUT_TERAPIA_SUCCESS';
export const PUT_TERAPIA_FAILURE = 'PUT_TERAPIA_FAILURE';


/* Pacientes */
export const FETCH_PACIENTES_SUCCESS = 'FETCH_PACIENTES_SUCCESS';
export const FETCH_PACIENTES_FAILURE = 'FETCH_PACIENTES_FAILURE';
export const ADD_PACIENTE_SUCCESS = 'ADD_PACIENTE_SUCCESS';
export const ADD_PACIENTE_FAILURE = 'ADD_PACIENTE_FAILURE';
export const FETCH_PACIENTE_DETALLE_SUCCESS = 'FETCH_PACIENTE_DETALLE_SUCCESS';
export const FETCH_PACIENTE_DETALLE_FAILURE = 'FETCH_PACIENTE_DETALLE_FAILURE';
export const UPDATE_PACIENTE_SUCCESS = 'UPDATE_PACIENTE_SUCCESS';
export const UPDATE_PACIENTE_FAILURE = 'UPDATE_PACIENTE_FAILURE';


/* Accounts */
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAIL = 'SIGNUP_FAIL';
export const ACTIVATION_SUCCESS = 'ACTIVATION_SUCCESS';
export const ACTIVATION_FAIL = 'ACTIVATION_FAIL';
export const USER_LOADED_SUCCESS = 'USER_LOADED_SUCCESS';
export const USER_LOADED_FAIL = 'USER_LOADED_FAIL';
export const AUTHENTICATED_SUCCESS = 'AUTHENTICATED_SUCCESS';
export const AUTHENTICATED_FAIL = 'AUTHENTICATED_FAIL';
export const PASSWORD_RESET_SUCCESS = 'PASSWORD_RESET_SUCCESS';
export const PASSWORD_RESET_FAIL = 'PASSWORD_RESET_FAIL';
export const PASSWORD_RESET_CONFIRM_FAIL = 'PASSWORD_RESET_CONFIRM_FAIL';
export const PASSWORD_RESET_CONFIRM_SUCCESS = 'PASSWORD_RESET_CONFIRM_SUCCESS';
export const LOGOUT = 'LOGOUT';





